//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquiry
    {
        public int InquiryID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Company { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string CompanyDesignation { get; set; }
        public int InquiryTypeID { get; set; }
        public string Details { get; set; }
        public Nullable<System.Guid> ReceivedBy { get; set; }
        public Nullable<System.DateTime> TimeCallReceived { get; set; }
        public Nullable<System.DateTime> TimeCallEnded { get; set; }
        public Nullable<bool> NeedFollowUp { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string PendingTask { get; set; }
        public Nullable<int> ActionID { get; set; }
        public string Status { get; set; }
    
        public virtual InquiryType InquiryType { get; set; }
    }
}
